// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDikOytCHSTGVt1_MnI6NiSNLoNqdrr3Hc',
    appId: '1:465456025590:web:40b631fb22e05a4e6a41d7',
    messagingSenderId: '465456025590',
    projectId: 'evently-app-bad66',
    authDomain: 'evently-app-bad66.firebaseapp.com',
    storageBucket: 'evently-app-bad66.firebasestorage.app',
    measurementId: 'G-EGKHHCFB7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1rwGaGQMBUMteyKilFKN2zIhq-VQIEeI',
    appId: '1:465456025590:android:43d45182e49b0f9f6a41d7',
    messagingSenderId: '465456025590',
    projectId: 'evently-app-bad66',
    storageBucket: 'evently-app-bad66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjDzOt1ht-CS7QI5IcWuL1LuoKp54sGrM',
    appId: '1:465456025590:ios:55aaec7ad3f5fb036a41d7',
    messagingSenderId: '465456025590',
    projectId: 'evently-app-bad66',
    storageBucket: 'evently-app-bad66.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );
}
